import {Router} from 'express'; import {body,param} from 'express-validator'; import {protect,authorize} from '../middleware/auth.js'; import Order from '../models/Order.js'; import * as generic from '../controllers/resourceController.js'; import * as m from '../controllers/managementController.js'; import * as pay from '../controllers/paymentController.js'; import {validate} from '../middleware/validate.js'; import {examUpload,subjectUpload,chapterUpload} from '../middleware/upload.js';
const r=Router(),admin=authorize('admin'),id=[param('id').isMongoId().withMessage('Invalid resource id')];
const examRules=[body('title').trim().notEmpty().withMessage('Name is required'),body('slug').optional().trim().matches(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).withMessage('Slug must use lowercase hyphens'),body('price').optional().isFloat({min:0}),body('discountPrice').optional().isFloat({min:0})]; const subjectRules=[body('name').trim().notEmpty(),body('exam').isMongoId(),body('displayOrder').optional().isInt({min:0})]; const chapterRules=[body('title').trim().notEmpty(),body('subject').isMongoId(),body('chapterNumber').optional().isInt({min:0}),body('pagesCount').optional().isInt({min:0})];
r.get('/exams/search',m.search('exams'));r.get('/subjects/search',m.search('subjects'));r.get('/chapters/search',m.search('chapters'));r.get('/admin/exams',protect,admin,m.list('exams'));r.get('/admin/subjects',protect,admin,m.list('subjects'));r.get('/admin/chapters',protect,admin,m.list('chapters'));r.get('/exams',m.list('exams'));r.get('/subjects',m.list('subjects'));r.get('/chapters',m.list('chapters'));r.get('/exams/slug/:slug',m.getExamBySlug);r.get('/exams/:id',id,validate,m.get('exams'));r.get('/subjects/:id',id,validate,m.get('subjects'));r.get('/chapters/:id',id,validate,m.get('chapters'));
for(const [key,upload,rules] of [['exams',examUpload,examRules],['subjects',subjectUpload,subjectRules],['chapters',chapterUpload,chapterRules]]){r.post(`/${key}`,protect,admin,upload,rules,validate,m.create(key));r.patch(`/${key}/:id`,protect,admin,upload,id,validate,m.update(key));r.delete(`/${key}/:id`,protect,admin,id,validate,m.remove(key))}
r.post('/chapters/bulk',protect,admin,body('ids').isArray({min:1}),body('action').isIn(['delete','publish','unpublish']),validate,m.bulkChapter);r.get('/admin/analytics',protect,admin,m.analytics);r.get('/admin/dashboard',protect,admin,m.analytics);
r.post('/payments/orders',protect,body('examId').isMongoId(),body('couponCode').optional().trim().isLength({max:30}),validate,pay.createOrder);r.post('/payments/verify',protect,body('razorpay_order_id').notEmpty(),body('razorpay_payment_id').notEmpty(),body('razorpay_signature').notEmpty(),validate,pay.verify);r.post('/payments/webhook',pay.webhook);r.get('/chapters/:id/access',protect,id,validate,pay.accessChapter);r.get('/purchases/my',protect,pay.myPurchases);r.get('/admin/reports',protect,admin,pay.reports);
for(const key of ['orders','notifications','coupons','sales','videos','reviews','settings']){r.get(`/${key}`,protect,admin,generic.list(key));r.post(`/${key}`,protect,admin,generic.create(key));r.patch(`/${key}/:id`,protect,admin,generic.update(key));r.delete(`/${key}/:id`,protect,admin,generic.remove(key))}r.get('/users',protect,admin,generic.list('users'));r.patch('/users/:id',protect,admin,generic.update('users'));r.delete('/users/:id',protect,admin,generic.remove('users'));
r.get('/wishlist',protect,generic.wishlist);r.post('/wishlist/:examId',protect,generic.toggleWishlist);r.get('/orders/my',protect,async(req,res,next)=>{try{res.json({success:true,data:await Order.find({user:req.user._id}).populate('exams.exam exam').sort('-createdAt')})}catch(e){next(e)}});r.get('/notifications/my',protect,async(req,res,next)=>{try{const N=(await import('../models/Notification.js')).default;res.json({success:true,data:await N.find({user:req.user._id}).sort('-createdAt')})}catch(e){next(e)}});r.get('/notifications/unread-count',protect,generic.unreadNotifications);export default r;
