import multer from 'multer'; import path from 'path'; import fs from 'fs/promises'; import crypto from 'crypto'; import cloudinary,{cloudinaryEnabled} from '../config/cloudinary.js';
const limit=Number(process.env.MAX_UPLOAD_SIZE_MB||20)*1024*1024;
const imageTypes=['image/jpeg','image/png','image/webp']; const pdfTypes=['application/pdf']; const videoTypes=['video/mp4','video/webm','video/quicktime'];
const uploader=multer({storage:multer.memoryStorage(),limits:{fileSize:limit},fileFilter:(req,file,cb)=>{const allowed=file.fieldname.toLowerCase().includes('pdf')?pdfTypes:file.fieldname.toLowerCase().includes('video')?videoTypes:imageTypes;cb(allowed.includes(file.mimetype)?null:new Error('Unsupported upload type'),allowed.includes(file.mimetype))}});
const uploadFiles=async(req,res,next)=>{try{const files=req.file?[req.file]:Object.values(req.files||{}).flat();if(!files.length)return next();for(const file of files){const safe=`${Date.now()}-${crypto.randomBytes(4).toString('hex')}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const kind=file.mimetype==='application/pdf'?'pdfs':file.mimetype.startsWith('video/')?'videos':'images';if(cloudinaryEnabled)await new Promise((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder:`competition-notes/${kind}`,resource_type:kind==='pdfs'?'raw':kind==='videos'?'video':'image',public_id:safe},(e,result)=>e?reject(e):resolve(Object.assign(file,{cloudinary:result})));stream.end(file.buffer)});else{const dir=path.resolve(process.cwd(),'uploads',kind);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,safe),file.buffer);Object.assign(file,{local:{url:`/uploads/${kind}/${safe}`,publicId:safe,format:path.extname(safe).slice(1)}})}}next()}catch(e){next(e)}};
const wrapped=m=>[(req,res,next)=>m(req,res,e=>e?next(e):uploadFiles(req,res,next))];
export const chapterUpload=wrapped(uploader.fields([{name:'samplePdf',maxCount:1},{name:'fullPdf',maxCount:1},{name:'sampleVideo',maxCount:1},{name:'sampleImages',maxCount:20},{name:'fullImages',maxCount:20}]));
export const examUpload=wrapped(uploader.fields([{name:'thumbnail',maxCount:1},{name:'banner',maxCount:1}])); export const subjectUpload=wrapped(uploader.single('image'));
export const toAsset=f=>f&&({url:f.cloudinary?.secure_url||f.local?.url,publicId:f.cloudinary?.public_id||f.local?.publicId,bytes:f.size,format:f.cloudinary?.format||f.local?.format,originalName:f.originalname});
